
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123QWEasd
 
  
development:
  database: depotdevelopment
  <<: *default

test:
  database: depottest
  <<: *default
 
production:
  database: depotproduction
  <<: *default
 